version: '3'
services:
  kanetix-test:
    build: .
    command: ["python", "app.py"]
    environment:
      - PYTHONUNBUFFERED=0
    hostname: kanetx-test
    image: kanetix-test:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app